/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "KalaGato",
  "tagline": "The Mobile App Portfolio Scaling Engine",
  "organizationName": "kalagato",
  "projectName": "portal",
  "baseUrl": "/",
  "baseUrlIssueBanner": true,
  "url": "https://docusaurus.io",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "trailingSlash": false,
  "stylesheets": [
    {
      "href": "/katex/katex.min.css",
      "type": "text/css"
    }
  ],
  "i18n": {
    "defaultLocale": "en",
    "localeConfigs": {
      "en": {
        "translate": true
      }
    },
    "locales": [
      "en",
      "fr",
      "pt-BR",
      "ko",
      "zh-CN"
    ],
    "path": "i18n"
  },
  "markdown": {
    "format": "detect",
    "mermaid": true,
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "mdx1Compat": {
      "admonitions": true,
      "comments": false,
      "headingIds": false
    },
    "remarkRehypeOptions": {
      "footnoteLabel": "Footnotes"
    },
    "emoji": true,
    "anchors": {
      "maintainCase": false
    }
  },
  "onBrokenLinks": "warn",
  "onBrokenAnchors": "warn",
  "favicon": "img/kalagato.svg",
  "customFields": {
    "crashTest": false,
    "isDeployPreview": false,
    "description": "An optimized site generator in React. Docusaurus helps you to move fast and write content. Build documentation websites, blogs, marketing pages, and more.",
    "announcedVersion": "3.10"
  },
  "staticDirectories": [
    "static",
    "/Users/abhishekdhobe/Code/kalagato/docusaurus/website/_dogfooding/_asset-tests",
    "/Users/abhishekdhobe/Code/kalagato/docusaurus/website/_dogfooding/non-existent"
  ],
  "themes": [
    "live-codeblock",
    null
  ],
  "plugins": [
    null,
    false,
    [
      "./src/plugins/changelog/index.ts",
      {
        "blogTitle": "Docusaurus changelog",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "blogDescription": "Keep yourself up-to-date about new features in every release",
        "blogSidebarCount": "ALL",
        "blogSidebarTitle": "Changelog",
        "routeBasePath": "/changelog",
        "showReadingTime": false,
        "postsPerPage": 20,
        "archiveBasePath": null,
        "authorsMapPath": "authors.json",
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus changelog",
          "description": "Keep yourself up-to-date about new features in every release",
          "copyright": "Copyright © 2026 Facebook, Inc.",
          "language": "en"
        },
        "onInlineAuthors": "warn"
      }
    ],
    [
      "content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "remarkPlugins": [
          null
        ],
        "editCurrentVersion": true,
        "sidebarPath": "./sidebarsCommunity.js",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "client-redirects",
      {
        "fromExtensions": [
          "html"
        ],
        "redirects": []
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ],
    [
      "pwa",
      {
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "swCustom": "/Users/abhishekdhobe/Code/kalagato/docusaurus/website/src/sw.js",
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "img/docusaurus.png"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "img/docusaurus.png",
            "color": "rgb(62, 204, 94)"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "img/docusaurus.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    "@docusaurus/theme-mermaid",
    "./src/plugins/featureRequests/FeatureRequestsPlugin.js",
    [
      "content-docs",
      {
        "id": "docs-tests",
        "routeBasePath": "/tests/docs",
        "sidebarPath": "_dogfooding/docs-tests-sidebars.js",
        "editUrl": "https://github.com/facebook/docusaurus/edit/main/website/",
        "versions": {
          "current": {
            "noIndex": true
          }
        },
        "onInlineTags": "warn",
        "tags": "tags.yml",
        "recmaPlugins": [
          [
            null,
            null
          ]
        ],
        "path": "_dogfooding/_docs tests",
        "showLastUpdateTime": false,
        "showLastUpdateAuthor": false
      }
    ],
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "blog-tests",
        "path": "_dogfooding/_blog tests",
        "routeBasePath": "/tests/blog",
        "editUrl": "https://github.com/facebook/docusaurus/edit/main/website/",
        "postsPerPage": 3,
        "blogSidebarCount": "ALL",
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus Tests Blog",
          "copyright": "Copyright © 2026 Facebook, Inc.",
          "xslt": {
            "rss": "custom-rss.xsl",
            "atom": "custom-atom.xsl"
          }
        },
        "onInlineTags": "warn",
        "onInlineAuthors": "ignore",
        "onUntruncatedBlogPosts": "ignore",
        "tags": "tags.yml"
      }
    ],
    [
      "/Users/abhishekdhobe/Code/kalagato/docusaurus/packages/docusaurus-plugin-content-pages/lib/index.js",
      {
        "id": "pages-tests",
        "path": "_dogfooding/_pages tests",
        "routeBasePath": "/tests/pages",
        "showLastUpdateTime": false,
        "showLastUpdateAuthor": false
      }
    ],
    null
  ],
  "presets": [
    [
      "classic",
      {
        "debug": true,
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.ts",
          "admonitions": {
            "keywords": [
              "my-custom-admonition"
            ]
          },
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ],
            null,
            null
          ],
          "rehypePlugins": [
            null
          ],
          "disableVersioning": true,
          "lastVersion": "current",
          "versions": {
            "current": {
              "label": "Canary 🚧"
            }
          }
        },
        "blog": {
          "path": "blog",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            null
          ],
          "postsPerPage": 5,
          "feedOptions": {
            "type": "all",
            "description": "Keep up to date with upcoming Docusaurus releases and articles by following our feed!",
            "copyright": "Copyright © 2026 Facebook, Inc.",
            "xslt": true
          },
          "blogTitle": "Docusaurus blog",
          "blogDescription": "Read blog posts about Docusaurus from the team",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts",
          "onUntruncatedBlogPosts": "warn",
          "onInlineTags": "warn"
        },
        "pages": {
          "remarkPlugins": [
            null
          ],
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": [
            "./src/css/custom.css",
            "./_dogfooding/dogfooding.css"
          ]
        },
        "gtag": {
          "trackingID": [
            "G-E5CR2Q1NRE"
          ]
        },
        "sitemap": {
          "ignorePatterns": [
            "/tests/{blog,pages}/**"
          ],
          "lastmod": "date",
          "priority": null,
          "changefreq": null
        },
        "svgr": {
          "svgrConfig": {}
        }
      }
    ]
  ],
  "themeConfig": {
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcementBar-v1_0_0",
      "content": "<b>KalaGato Internal Knowledge Base &amp; SOP Playbook Center</b>",
      "isCloseable": true
    },
    "prism": {
      "additionalLanguages": [
        "java",
        "latex",
        "haskell",
        "matlab",
        "php",
        "powershell",
        "bash",
        "diff",
        "json",
        "scss"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ],
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#0550AE",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "parameter"
            ],
            "style": {
              "color": "#953800"
            }
          },
          {
            "types": [
              "boolean",
              "rule",
              "color",
              "number",
              "constant",
              "property"
            ],
            "style": {
              "color": "#005CC5"
            }
          },
          {
            "types": [
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#22863A"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#24292E"
            }
          },
          {
            "types": [
              "operator",
              "unit",
              "rule"
            ],
            "style": {
              "color": "#D73A49"
            }
          },
          {
            "types": [
              "font-matter",
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#C6105F"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "#116329"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#0550AE"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#CF222E"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#8250DF"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "#6F42C1"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#E36209"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#6B6B6B"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#D4D4D4",
          "backgroundColor": "#212121"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#569CD6",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "property",
              "parameter"
            ],
            "style": {
              "color": "#9CDCFE"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#D4D4D4"
            }
          },
          {
            "types": [
              "boolean",
              "arrow",
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#569CD6"
            }
          },
          {
            "types": [
              "number",
              "color",
              "unit"
            ],
            "style": {
              "color": "#B5CEA8"
            }
          },
          {
            "types": [
              "font-matter"
            ],
            "style": {
              "color": "#CE9178"
            }
          },
          {
            "types": [
              "keyword",
              "rule"
            ],
            "style": {
              "color": "#C586C0"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#D16969"
            }
          },
          {
            "types": [
              "maybe-class-name"
            ],
            "style": {
              "color": "#4EC9B0"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "#4FC1FF"
            }
          }
        ]
      }
    },
    "image": "img/docusaurus-social-card.jpg",
    "algolia": {
      "appId": "X1Z85QJPUV",
      "apiKey": "bf7211c161e8205da2f933a02534105a",
      "indexName": "docusaurus-2",
      "askAi": {
        "assistantId": "RgIMYFUmTfrN",
        "indexName": "docusaurus-markdown",
        "suggestedQuestions": true,
        "apiKey": "bf7211c161e8205da2f933a02534105a",
        "appId": "X1Z85QJPUV"
      },
      "replaceSearchResultPathname": {
        "from": "\\^\\\\/docs\\\\/next",
        "to": "/docs"
      },
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "KalaGato",
      "logo": {
        "alt": "KalaGato Logo",
        "src": "img/kalagato.svg",
        "srcDark": "img/kalagato.svg",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "type": "doc",
          "position": "left",
          "docId": "introduction",
          "label": "Docs"
        },
        {
          "to": "/human-org",
          "label": "Human Org Chart",
          "position": "left"
        },
        {
          "to": "/editor",
          "label": "Docs Editor",
          "position": "left"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Introduction",
              "to": "docs"
            },
            {
              "label": "Human Org & SOPs",
              "to": "docs/human_org"
            },
            {
              "label": "Agentic Blueprint",
              "to": "docs/agent_org"
            },
            {
              "label": "Release SOP",
              "to": "docs/human_org/release-sop"
            }
          ]
        },
        {
          "title": "Operations",
          "items": [
            {
              "label": "Incident Management",
              "to": "docs/human_org/incident-management"
            },
            {
              "label": "Employee Policies",
              "to": "docs/human_org/employee-policies"
            },
            {
              "label": "M&A Due Diligence",
              "to": "docs/human_org/due-diligence"
            },
            {
              "label": "AdMob Playbook",
              "to": "docs/human_org/admob-playbook"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "KalaGato Website",
              "href": "https://www.kalagato.ai"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/kalagato"
            },
            {
              "label": "Contact Us",
              "href": "mailto:hello@kalagato.co"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy Policy",
              "href": "https://www.kalagato.ai/privacy-policy"
            },
            {
              "label": "Terms of Service",
              "href": "https://www.kalagato.ai/terms"
            }
          ]
        }
      ],
      "logo": {
        "alt": "KalaGato Logo",
        "src": "/img/kalagato.svg",
        "href": "https://kalagato.ai",
        "width": 60,
        "height": 60
      },
      "copyright": "Copyright © 2026 KalaGato (Human Data SG Pte. Ltd.). All Rights Reserved."
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
